/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MonopolyBoard;

import javax.swing.Icon;
import javax.swing.JLabel;

/**
 *
 * @author tonychiu
 */
public class MonopolyBoard extends javax.swing.JFrame {

    /**
     * Creates new form MonopolyBoard
     */
    public MonopolyBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayerPanelMain = new javax.swing.JPanel();
        selectedPlayerPanel = new javax.swing.JPanel();
        selectedPlayerInfo = new javax.swing.JPanel();
        selectedPlayerIcon = new javax.swing.JLabel();
        selectedPlayerName = new javax.swing.JLabel();
        selectedPlayerCash = new javax.swing.JLabel();
        selectedPlayerPropertyPanel = new javax.swing.JPanel();
        selectedBoardPiecePanel = new javax.swing.JPanel();
        selectedBoardPieceIconPanel = new javax.swing.JPanel();
        selectedBoardPieceIcon = new javax.swing.JLabel();
        monoboardBaseLayer = new javax.swing.JLayeredPane();
        monoboard = new javax.swing.JPanel();
        brown1 = new javax.swing.JLabel();
        corner_jail = new javax.swing.JLabel();
        teal3 = new javax.swing.JLabel();
        teal2 = new javax.swing.JLabel();
        chance1 = new javax.swing.JLabel();
        teal1 = new javax.swing.JLabel();
        rail1 = new javax.swing.JLabel();
        incomeTax = new javax.swing.JLabel();
        brown2 = new javax.swing.JLabel();
        chest1 = new javax.swing.JLabel();
        corner_go = new javax.swing.JLabel();
        pink1 = new javax.swing.JLabel();
        pink2 = new javax.swing.JLabel();
        electric = new javax.swing.JLabel();
        pink3 = new javax.swing.JLabel();
        rail2 = new javax.swing.JLabel();
        orange1 = new javax.swing.JLabel();
        chest2 = new javax.swing.JLabel();
        orange2 = new javax.swing.JLabel();
        orange3 = new javax.swing.JLabel();
        red1 = new javax.swing.JLabel();
        chance2 = new javax.swing.JLabel();
        red2 = new javax.swing.JLabel();
        red3 = new javax.swing.JLabel();
        rail3 = new javax.swing.JLabel();
        yellow1 = new javax.swing.JLabel();
        yellow2 = new javax.swing.JLabel();
        water = new javax.swing.JLabel();
        yellow3 = new javax.swing.JLabel();
        jail = new javax.swing.JLabel();
        green1 = new javax.swing.JLabel();
        green2 = new javax.swing.JLabel();
        chest3 = new javax.swing.JLabel();
        rail4 = new javax.swing.JLabel();
        chance3 = new javax.swing.JLabel();
        blue1 = new javax.swing.JLabel();
        luxaryTax = new javax.swing.JLabel();
        green3 = new javax.swing.JLabel();
        blue2 = new javax.swing.JLabel();
        freeparking = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlayerPanelMain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        selectedPlayerPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        selectedPlayerInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        selectedPlayerIcon.setText("jLabel1");

        selectedPlayerName.setText("James");

        selectedPlayerCash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cash.png"))); // NOI18N
        selectedPlayerCash.setText("jLabel1");

        javax.swing.GroupLayout selectedPlayerInfoLayout = new javax.swing.GroupLayout(selectedPlayerInfo);
        selectedPlayerInfo.setLayout(selectedPlayerInfoLayout);
        selectedPlayerInfoLayout.setHorizontalGroup(
            selectedPlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedPlayerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedPlayerIcon)
                .addGap(18, 18, 18)
                .addComponent(selectedPlayerName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectedPlayerInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectedPlayerCash)
                .addContainerGap())
        );
        selectedPlayerInfoLayout.setVerticalGroup(
            selectedPlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedPlayerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selectedPlayerInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectedPlayerIcon)
                    .addComponent(selectedPlayerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedPlayerCash)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        selectedPlayerPropertyPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        javax.swing.GroupLayout selectedPlayerPropertyPanelLayout = new javax.swing.GroupLayout(selectedPlayerPropertyPanel);
        selectedPlayerPropertyPanel.setLayout(selectedPlayerPropertyPanelLayout);
        selectedPlayerPropertyPanelLayout.setHorizontalGroup(
            selectedPlayerPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        selectedPlayerPropertyPanelLayout.setVerticalGroup(
            selectedPlayerPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout selectedPlayerPanelLayout = new javax.swing.GroupLayout(selectedPlayerPanel);
        selectedPlayerPanel.setLayout(selectedPlayerPanelLayout);
        selectedPlayerPanelLayout.setHorizontalGroup(
            selectedPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectedPlayerInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(selectedPlayerPropertyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        selectedPlayerPanelLayout.setVerticalGroup(
            selectedPlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedPlayerPanelLayout.createSequentialGroup()
                .addComponent(selectedPlayerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedPlayerPropertyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PlayerPanelMainLayout = new javax.swing.GroupLayout(PlayerPanelMain);
        PlayerPanelMain.setLayout(PlayerPanelMainLayout);
        PlayerPanelMainLayout.setHorizontalGroup(
            PlayerPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedPlayerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PlayerPanelMainLayout.setVerticalGroup(
            PlayerPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanelMainLayout.createSequentialGroup()
                .addComponent(selectedPlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 324, Short.MAX_VALUE))
        );

        selectedBoardPiecePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        selectedBoardPieceIconPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        selectedBoardPieceIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Go.png"))); // NOI18N

        javax.swing.GroupLayout selectedBoardPieceIconPanelLayout = new javax.swing.GroupLayout(selectedBoardPieceIconPanel);
        selectedBoardPieceIconPanel.setLayout(selectedBoardPieceIconPanelLayout);
        selectedBoardPieceIconPanelLayout.setHorizontalGroup(
            selectedBoardPieceIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedBoardPieceIconPanelLayout.createSequentialGroup()
                .addComponent(selectedBoardPieceIcon)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        selectedBoardPieceIconPanelLayout.setVerticalGroup(
            selectedBoardPieceIconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedBoardPieceIconPanelLayout.createSequentialGroup()
                .addComponent(selectedBoardPieceIcon)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout selectedBoardPiecePanelLayout = new javax.swing.GroupLayout(selectedBoardPiecePanel);
        selectedBoardPiecePanel.setLayout(selectedBoardPiecePanelLayout);
        selectedBoardPiecePanelLayout.setHorizontalGroup(
            selectedBoardPiecePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectedBoardPiecePanelLayout.createSequentialGroup()
                .addComponent(selectedBoardPieceIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        selectedBoardPiecePanelLayout.setVerticalGroup(
            selectedBoardPiecePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(selectedBoardPieceIconPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        monoboard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));
        monoboard.setAlignmentX(0.0F);
        monoboard.setAlignmentY(0.0F);
        monoboard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        monoboard.setPreferredSize(new java.awt.Dimension(734, 700));

        brown1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brown1.png"))); // NOI18N
        brown1.setToolTipText("");
        brown1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        corner_jail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/jail.png"))); // NOI18N
        corner_jail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        teal3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teal3.png"))); // NOI18N
        teal3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        teal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teal2.png"))); // NOI18N
        teal2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        chance1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chance1.png"))); // NOI18N
        chance1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        teal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/teal3.png"))); // NOI18N
        teal1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        rail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rail1.png"))); // NOI18N
        rail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        incomeTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/incometax.png"))); // NOI18N
        incomeTax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        brown2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/brown2.png"))); // NOI18N
        brown2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        chest1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/communityChest1.png"))); // NOI18N
        chest1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        corner_go.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Go.png"))); // NOI18N
        corner_go.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        corner_go.setName("go_corner"); // NOI18N
        corner_go.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        pink1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pink1.png"))); // NOI18N
        pink1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        pink2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pink2.png"))); // NOI18N
        pink2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        electric.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/electric.png"))); // NOI18N
        electric.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        pink3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pink3.png"))); // NOI18N
        pink3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        rail2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rail2.png"))); // NOI18N
        rail2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        orange1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orange1.png"))); // NOI18N
        orange1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        chest2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/communityChest2.png"))); // NOI18N
        chest2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        orange2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orange2.png"))); // NOI18N
        orange2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        orange3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/orange3.png"))); // NOI18N
        orange3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        red1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/red1.png"))); // NOI18N
        red1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        chance2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chance2.png"))); // NOI18N
        chance2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        red2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/red2.png"))); // NOI18N
        red2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        red3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/red3.png"))); // NOI18N
        red3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        rail3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rail3.png"))); // NOI18N

        yellow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yellow1.png"))); // NOI18N

        yellow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yellow2.png"))); // NOI18N

        water.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/water.png"))); // NOI18N

        yellow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/yellow3.png"))); // NOI18N

        jail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gojail.png"))); // NOI18N

        green1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/green1.png"))); // NOI18N

        green2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/green2.png"))); // NOI18N

        chest3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/communityChest3.png"))); // NOI18N

        rail4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rail4.png"))); // NOI18N

        chance3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/chance3.png"))); // NOI18N

        blue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue1.png"))); // NOI18N

        luxaryTax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/luxaryTax.png"))); // NOI18N

        green3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/green3.png"))); // NOI18N

        blue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue2.png"))); // NOI18N

        freeparking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/freeparking.png"))); // NOI18N
        freeparking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickedBoardPiece(evt);
            }
        });

        javax.swing.GroupLayout monoboardLayout = new javax.swing.GroupLayout(monoboard);
        monoboard.setLayout(monoboardLayout);
        monoboardLayout.setHorizontalGroup(
            monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monoboardLayout.createSequentialGroup()
                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monoboardLayout.createSequentialGroup()
                        .addComponent(rail2)
                        .addGap(544, 544, 544)
                        .addComponent(rail4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(monoboardLayout.createSequentialGroup()
                        .addComponent(pink3)
                        .addGap(544, 544, 544)
                        .addComponent(chance3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(monoboardLayout.createSequentialGroup()
                        .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pink2)
                            .addGroup(monoboardLayout.createSequentialGroup()
                                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, monoboardLayout.createSequentialGroup()
                                        .addComponent(electric)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pink1)
                                        .addGroup(monoboardLayout.createSequentialGroup()
                                            .addComponent(corner_jail)
                                            .addGap(3, 3, 3)
                                            .addComponent(teal3)
                                            .addGap(1, 1, 1)
                                            .addComponent(teal2)
                                            .addGap(0, 0, 0)
                                            .addComponent(chance1)
                                            .addGap(0, 0, 0)
                                            .addComponent(teal1)
                                            .addGap(2, 2, 2)
                                            .addComponent(rail1))))
                                .addComponent(incomeTax)
                                .addGap(0, 0, 0)
                                .addComponent(brown2)
                                .addGap(0, 0, 0)
                                .addComponent(chest1)))
                        .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(monoboardLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(monoboardLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(blue1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(luxaryTax, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(blue2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(monoboardLayout.createSequentialGroup()
                                .addComponent(brown1)
                                .addGap(0, 0, 0)
                                .addComponent(corner_go))))
                    .addGroup(monoboardLayout.createSequentialGroup()
                        .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(monoboardLayout.createSequentialGroup()
                                .addComponent(freeparking)
                                .addGap(0, 0, 0)
                                .addComponent(red1)
                                .addGap(1, 1, 1)
                                .addComponent(chance2)
                                .addGap(0, 0, 0)
                                .addComponent(red2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, monoboardLayout.createSequentialGroup()
                                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chest2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orange1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(monoboardLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(red3)
                                .addGap(0, 0, 0)
                                .addComponent(rail3)
                                .addGap(0, 0, 0)
                                .addComponent(yellow1)
                                .addGap(0, 0, 0)
                                .addComponent(yellow2)
                                .addGap(0, 0, 0)
                                .addComponent(water)
                                .addGap(0, 0, 0)
                                .addComponent(yellow3)
                                .addGap(0, 0, 0)
                                .addComponent(jail))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monoboardLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chest3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(green3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(monoboardLayout.createSequentialGroup()
                        .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orange3)
                            .addComponent(orange2))
                        .addGap(542, 542, 542)
                        .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(green2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(green1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );
        monoboardLayout.setVerticalGroup(
            monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monoboardLayout.createSequentialGroup()
                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(red1)
                    .addComponent(chance2)
                    .addComponent(red2)
                    .addComponent(red3)
                    .addComponent(rail3)
                    .addComponent(yellow1)
                    .addComponent(yellow2)
                    .addComponent(water)
                    .addComponent(yellow3)
                    .addComponent(jail)
                    .addComponent(freeparking))
                .addGap(0, 0, 0)
                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orange3)
                    .addComponent(green1))
                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orange2)
                    .addComponent(green2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chest2)
                    .addComponent(chest3))
                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orange1)
                    .addComponent(green3))
                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rail2)
                    .addComponent(rail4))
                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pink3)
                    .addComponent(chance3))
                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monoboardLayout.createSequentialGroup()
                        .addComponent(pink2)
                        .addGap(0, 0, 0)
                        .addComponent(electric)
                        .addGap(0, 0, 0)
                        .addComponent(pink1))
                    .addGroup(monoboardLayout.createSequentialGroup()
                        .addComponent(blue1)
                        .addGap(2, 2, 2)
                        .addComponent(luxaryTax)
                        .addGap(0, 0, 0)
                        .addComponent(blue2)))
                .addGap(0, 0, 0)
                .addGroup(monoboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corner_jail)
                    .addComponent(teal3)
                    .addComponent(teal2)
                    .addComponent(chance1)
                    .addComponent(teal1)
                    .addComponent(rail1)
                    .addComponent(incomeTax)
                    .addComponent(brown2)
                    .addComponent(chest1)
                    .addComponent(brown1)
                    .addComponent(corner_go)))
        );

        brown2.getAccessibleContext().setAccessibleDescription("");
        corner_go.getAccessibleContext().setAccessibleName("corner_go");

        monoboard.setBounds(0, 0, 734, 730);
        monoboardBaseLayer.add(monoboard, new Integer(1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/freeparking.png"))); // NOI18N
        jLabel2.setBounds(300, 300, 92, 92);
        monoboardBaseLayer.add(jLabel2, new Integer(3));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dog.png"))); // NOI18N
        jLabel1.setBounds(360, 360, 29, 30);
        monoboardBaseLayer.add(jLabel1, new Integer(2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monoboardBaseLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedBoardPiecePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayerPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selectedBoardPiecePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(PlayerPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(monoboardBaseLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Update the icon of a target label with a new icon **/
    private void updateLabelIcon(JLabel targetLabel, String newIcon) {
        // Remove the prev Icon first
        targetLabel.setIcon(null);
        // Set the new icon
        System.out.println(newIcon);
        targetLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/"+newIcon)));
        targetLabel.revalidate();
    }
    
    private void clickedBoardPiece(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickedBoardPiece
        // TODO add your handling code here:
        JLabel lb = (JLabel)evt.getSource();
        String[] trimmedPath = new String[2];
        trimmedPath = lb.getIcon().toString().split("/Images/");
        
        updateLabelIcon(selectedBoardPieceIcon, trimmedPath[1]);
    }//GEN-LAST:event_clickedBoardPiece

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonopolyBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonopolyBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonopolyBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonopolyBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonopolyBoard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PlayerPanelMain;
    private javax.swing.JLabel blue1;
    private javax.swing.JLabel blue2;
    private javax.swing.JLabel brown1;
    private javax.swing.JLabel brown2;
    private javax.swing.JLabel chance1;
    private javax.swing.JLabel chance2;
    private javax.swing.JLabel chance3;
    private javax.swing.JLabel chest1;
    private javax.swing.JLabel chest2;
    private javax.swing.JLabel chest3;
    private javax.swing.JLabel corner_go;
    private javax.swing.JLabel corner_jail;
    private javax.swing.JLabel electric;
    private javax.swing.JLabel freeparking;
    private javax.swing.JLabel green1;
    private javax.swing.JLabel green2;
    private javax.swing.JLabel green3;
    private javax.swing.JLabel incomeTax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jail;
    private javax.swing.JLabel luxaryTax;
    private javax.swing.JPanel monoboard;
    private javax.swing.JLayeredPane monoboardBaseLayer;
    private javax.swing.JLabel orange1;
    private javax.swing.JLabel orange2;
    private javax.swing.JLabel orange3;
    private javax.swing.JLabel pink1;
    private javax.swing.JLabel pink2;
    private javax.swing.JLabel pink3;
    private javax.swing.JLabel rail1;
    private javax.swing.JLabel rail2;
    private javax.swing.JLabel rail3;
    private javax.swing.JLabel rail4;
    private javax.swing.JLabel red1;
    private javax.swing.JLabel red2;
    private javax.swing.JLabel red3;
    private javax.swing.JLabel selectedBoardPieceIcon;
    private javax.swing.JPanel selectedBoardPieceIconPanel;
    private javax.swing.JPanel selectedBoardPiecePanel;
    private javax.swing.JLabel selectedPlayerCash;
    private javax.swing.JLabel selectedPlayerIcon;
    private javax.swing.JPanel selectedPlayerInfo;
    private javax.swing.JLabel selectedPlayerName;
    private javax.swing.JPanel selectedPlayerPanel;
    private javax.swing.JPanel selectedPlayerPropertyPanel;
    private javax.swing.JLabel teal1;
    private javax.swing.JLabel teal2;
    private javax.swing.JLabel teal3;
    private javax.swing.JLabel water;
    private javax.swing.JLabel yellow1;
    private javax.swing.JLabel yellow2;
    private javax.swing.JLabel yellow3;
    // End of variables declaration//GEN-END:variables
}
